#!/usr/bin/env node
/**
 * Builds SKILL.md for an AI agent out of src/blocks/schema.json.
 *
 * Why generate rather than hand-write: the agent documentation IS the block
 * contract. Written by hand, it drifts away from the code within a couple of
 * releases, and the agent starts confidently inventing keys that do not exist.
 *
 * Two audiences, one body: Claude Code reads SKILL.md, everything else reads
 * AGENTS.md. Only the wrapper differs, so the reference cannot drift between
 * them.
 *
 * Writes:
 *   src/skill/skill-content.ts  — what the plugin drops into the vault
 *   docs/dashy.schema.json      — a machine-readable copy for any other tool
 *
 * `--check` writes nothing and fails when the generated output differs from
 * what is committed. That is the gate catching "edited the schema, forgot to
 * rebuild".
 */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const schema = JSON.parse(fs.readFileSync(path.join(root, "src/blocks/schema.json"), "utf8"));
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const check = process.argv.includes("--check");

const SKILL_PATH = ".claude/skills/dashy/SKILL.md";
const AGENTS_PATH = "AGENTS.md";

/**
 * AGENTS.md belongs to the vault, not to us: other tools write there too. The
 * section is fenced so it can be replaced on update without touching a line
 * the user put around it.
 */
const AGENTS_BEGIN = "<!-- dashy:begin -->";
const AGENTS_END = "<!-- dashy:end -->";

/** A pipe inside a cell breaks the markdown table — escape it. */
function cell(v) {
    return String(v).replace(/\|/g, "\\|");
}

function fields(map) {
    const rows = Object.entries(map).map(([key, f]) => {
        const req = f.required ? "yes" : "—";
        const def = f.default !== undefined ? `\`${cell(f.default)}\`` : "—";
        const alias = f.aliases ? f.aliases.map((a) => `\`${a}\``).join(", ") : "—";
        return `| \`${key}\` | ${cell(f.type)} | ${req} | ${def} | ${alias} | ${cell(f.doc)} |`;
    });
    return ["| key | type | required | default | synonyms | what it does |",
            "|---|---|---|---|---|---|", ...rows].join("\n");
}

function blockSection(name, b) {
    const parts = [`### \`${name}\``, "", b.summary, ""];
    if (b.root) parts.push("**Block root**", "", fields(b.root), "");
    if (b.item) parts.push("**List item**", "", fields(b.item), "");
    parts.push("**Example**", "", "````markdown", "```" + name, b.example, "```", "````", "");
    if (b.notes) parts.push(...b.notes.map((n) => `- ${n}`), "");
    return parts.join("\n");
}

const blocks = Object.entries(schema.blocks);

const reference = `# Dashy — dashboard blocks

The **${manifest.name}** plugin (\`${manifest.id}\`) draws a dashboard out of
markdown blocks. The config is YAML inside the block. No JavaScript, and no
Dataview required.

Blocks in total: ${blocks.length}.

${blocks.map(([n, b]) => blockSection(n, b)).join("\n")}
## What the plugin does NOT do

Do not invent blocks that do not exist. If asked for something on this list,
say what actually does the job.

${Object.entries(schema.notInV1).map(([k, v]) => `- **${k}** — ${v}`).join("\n")}

## General rules

- Quote values containing a colon, a comma or a hash: \`label: "Home: entry"\`.
- The key synonyms in the tables above are recognised, but write the canonical key in new configs.
- An unknown key does not break the block — a warning is drawn instead. Still, stray keys do not belong there.
- A block prints its own config errors straight into the note. If the user pastes an error, read it literally: it carries the line number.

The plugin speaks the language of the Obsidian interface. These blocks and keys
are the same in every language.
`;

const markdown = `---
name: dashy
description: >-
  Build a dashboard inside an Obsidian note with Dashy blocks: a grid of
  navigation tiles, number cards computed from frontmatter, a day row linking
  to the daily, weekly and monthly notes, and a year heatmap. Use it when asked
  for a dashboard, a home page, a tile grid, cards with counters or averages, a
  link to today's note, a day calendar, a heatmap, a habit tracker or a visual
  entry point into the vault.
version: ${schema.version}
---

${reference}`;

const agents = `${AGENTS_BEGIN}
<!-- Generated by the ${manifest.name} plugin, version ${schema.version}.
     Everything between these two markers is replaced on update; anything
     outside them is left alone. -->

${reference}
${AGENTS_END}`;

const contentTs = `/**
 * WARNING: this file is generated by \`npm run build:skill\` from
 * src/blocks/schema.json. Do not edit by hand — the edit is lost on the next
 * build and the documentation drifts away from the behaviour. That is exactly
 * how agent instructions go stale.
 */
export const SKILL_VERSION = ${JSON.stringify(schema.version)};
export const SKILL_PATH = ${JSON.stringify(SKILL_PATH)};
export const SKILL_MARKDOWN = ${JSON.stringify(markdown)};
export const AGENTS_PATH = ${JSON.stringify(AGENTS_PATH)};
export const AGENTS_SECTION = ${JSON.stringify(agents)};
export const AGENTS_BEGIN = ${JSON.stringify(AGENTS_BEGIN)};
export const AGENTS_END = ${JSON.stringify(AGENTS_END)};
`;

const targets = [
    { file: "src/skill/skill-content.ts", body: contentTs },
    { file: "docs/dashy.schema.json", body: JSON.stringify(schema, null, 2) + "\n" },
    { file: "docs/SKILL.preview.md", body: markdown },
    { file: "docs/AGENTS.preview.md", body: agents + "\n" },
];

let stale = [];
for (const t of targets) {
    const full = path.join(root, t.file);
    const current = fs.existsSync(full) ? fs.readFileSync(full, "utf8") : null;
    if (current === t.body) continue;
    if (check) { stale.push(t.file); continue; }
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, t.body, "utf8");
    console.log(`[${manifest.id}] wrote ${t.file}`);
}

if (check && stale.length) {
    console.error(`[${manifest.id}] skill is out of sync with the schema: ${stale.join(", ")}`);
    console.error(`[${manifest.id}] run: npm run build:skill`);
    process.exit(1);
}
if (check) console.log(`[${manifest.id}] skill is in sync with the schema`);
